### ISSUE TITLE
Import of backup file fails

### ISSUE THREAD

**Issue by Hubertilus** [SmartReceipts/SmartReceiptsLibrary#259]
Hello,

due to a reboot issue i needed to do a factory reset my Android mobile phone. Before doing that, I created a local backup of my Smart Receipts data. After installing Smart Receipts on the reset phone, I tried importing the backup file. The import fails with the erro message "Error: The file was not detected as importable" (original German message "Fehler: Die Datei wurde nicht als importierbar erkannt."). And it makes no difference if I select the checkbox for overwriting existing data.

So that is a hard fact for me. But I tried to import older backups. I'm having backups from these dates:
  2021-02-13 not working
  2021-02-01 not working
  2021-01-05 not working
  2020-10-05 working
  2020-08-31 working
  ...
I'm currently running Version 4.21.0.2321. But I had regularly updated my Software during that time. So I cannot tell, which backup was created using which Smart Receipts version.

Can you please help me to get my backup data back into the App?
Whats the best way of helping you to debug the issue?
The backup file size is about 130 to 145 MB, and I would like to avoid sending it around.
DO I have the possibility to extract information form the latest backup tool using shell tools like they are available under Linux?

**Comment by Hubertilus** [comment]
I just tried opening the backup file with midnight commander and found, that it is a ZIP archive including files like .jpg, .xml and Database backup files. At least the ZIP file can be extracted using ZIP without any error message. So the ZIP seems not to be corrupted.

**Comment by Hubertilus** [comment]
I did another test.

1. After resetting the Smart Receipt App (Via Android Settings->App menu),
2. I imported the working backup from 2020-10-05 (241.5 MB).
3. Afterwards I created a new backup file. But now it's 357.8 MB size.
4. I reset the Smart Receipts App again.
5. Importing the new file works fine.

Hm, so I tried another case:
1. After resetting the Smart Receipt App (Via Android Settings->App menu),
2. I imported the working backup from 2020-10-05 (241.5 MB).
3. Now I added 10 new receipts with Photo.
4. Afterwards I created a new backup file. Now it has 484.9 MB size.
4. I reset the Smart Receipts App again.
5. Importing the new file again works fine.

So the export/import feature seems not to be broken.
But I'm wondering why the backup file increases by 116 MB when exporting same data again. And why it increases by another 120 MB when adding 10 receipts with photos. Especially when taking into account, that the new Photos (.jpg file) in the backup file are only taking 6 MB of size (unzipped).

Hope that helps tracking down the root cause of my issue.

**Comment by HeinousGames** [comment]
Hi @Hubertilus 

Please try updating to our new version from the Beta channel, the version is 4.21.1.2500. You can download it by following these instructions:

1. Open Google Play Store and go to Smart Receipts app page
2. Scroll to the bottom to find a beta section
3. Tap the Join button and follow any instructions Google gives you
4. After you successfully join you can see a new update to Smart Receipts in the My Apps and Updates section

This new version might allow you to import the backups that aren't successfully being imported. I believe we fixed the backup doubling issue awhile ago, but we might've missed something. It should be resolved in this new update as well. Please download it and let me know if you are still experiencing issues. You can get faster responses if you reach out to us at support@smartreceipts.co.

**Comment by Hubertilus** [comment]
Uhh, sorry. Forgot to give feedback.
That version mentioned above fixed my issue.
